apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-template-config
data:
  APP_NAME: ${APP_NAME}
  ENVIRONMENT: ${ENVIRONMENT}
  LOG_LEVEL: ${LOG_LEVEL}
  SQLALCHEMY_ECHO: "false"
  ENABLE_METRICS: "true"
