apiVersion: v1
kind: Secret
metadata:
  name: fastapi-template-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_RELEASE_NAME}-postgresql.${NAMESPACE}.svc.cluster.local:5432/${POSTGRES_DB}
